【fix】生年月日のバリデーションを修正
hiroaki514/BeeBits pull request #44
Opened 2024-01-26 16:46 UTC by hiroaki514

## PRの目的
生年月日のバリデーションが意図した状態と異なっていたため修正を行いました。
想定された以下の条件を許容します。

・生年月日欄が空欄で無いこと
・上記かつ現時点の日時において15歳以上であること

## 重点的に見て欲しいポイント

## 対象のissues

## 備考

2024-01-26 16:46 UTC, hiroaki514 commented
@yoshichiba 
生年月日に関するバリデーションを修正しました、ご確認よろしくお願いします。

2024-01-27 01:31 UTC, hiroaki514 commented
@yoshichiba
生年月日に関するバリデーションを修正しました、ご確認よろしくお願いします。

2024-01-27 10:17 UTC, yoshichiba requested changes
バリデーション以外の余計な差分が入ってしまっているので、そちらはPRに上がらないように修正してください！

2024-01-27 10:32 UTC, hiroaki514 commented
@yoshichiba 
不要な差分を修正しました、よろしくお願いします！

2024-01-27 10:40 UTC, yoshichiba commented on app/models/user.rb
>    end
```ruby
validates :birthday, presence: true

private

def validate_birthdate
  return if birthdate.blank?

  errors.add(:birthdate, 'が15歳未満の方はご利用いただけません') if birthdate > 15.years.ago.to_date
end
```

2024-01-27 10:40 UTC, yoshichiba commented on app/models/user.rb
>    end
できるだけrailsが持っているバリデーション（`validates :birthday, presence: true` ）を使用したいため、このようにすると良いかと思います。

2024-01-27 10:52 UTC, hiroaki514 commented on app/models/user.rb
>    end
validates :birthday, presence: trueが基本の形なのですね。
ありがとうございます！

2024-01-27 10:53 UTC, hiroaki514 commented
@yoshichiba 
こちらアドバイス頂いた形に修正しました！
挙動も確認済みです。

2024-01-27 11:07 UTC, yoshichiba approved these changes

2024-01-27 11:07 UTC, merged