【fix】ユーザー登録の際にbeebits_nameへの＠挿入を自動化するよう修正
hiroaki514/BeeBits pull request #45
Opened 2024-01-26 16:47 UTC by hiroaki514

## PRの目的
ユーザーの新規登録時にbeebits_nameの冒頭に＠を自動挿入するように修正します

## 重点的に見て欲しいポイント

## 対象のissues

## 備考

2024-01-26 17:19 UTC, hiroaki514 commented
@yoshichiba 
ユーザー登録時に手動で＠を入力せずとも冒頭に＠が入った状態で登録されるように修正しました。
入力欄への＠表示は今後Reactでフロント作成時に行いたいと思いますので表示させていません、よろしくお願いします！

2024-01-26 17:36 UTC, hiroaki514 commented
@yoshichiba
ユーザー登録時に手動で＠を入力せずとも冒頭に＠が入った状態で登録されるように修正しました。
入力欄への＠表示は今後Reactでフロント作成時に行いたいと思いますので表示させていません、よろしくお願いします！

2024-01-27 01:31 UTC, hiroaki514 commented
@yoshichiba
ユーザー登録時に手動で＠を入力せずとも冒頭に＠が入った状態で登録されるように修正しました。
入力欄への＠表示は今後Reactでフロント作成時に行いたいと思いますので表示させていません、よろしくお願いします！

2024-01-27 10:18 UTC, yoshichiba requested changes
> バリデーション以外の余計な差分が入ってしまっているので、そちらはPRに上がらないように修正してください！

こちらもお願いします！

2024-01-27 10:39 UTC, hiroaki514 commented
@yoshichiba 
こちらも修正しました！

2024-01-27 10:47 UTC, yoshichiba approved these changes

2024-01-27 10:47 UTC, yoshichiba commented on app/views/devise/registrations/new.html.erb
> +    <%= f.text_field :beebits_name, id: 'beebits_name_input', autocomplete: 'off' %>
idとautocompleteは現時点では不要だと思うので削除していただけますと！

2024-01-27 10:47 UTC, yoshichiba commented on app/models/user.rb
> +  before_validation :prepend_at_to_beebits_name
before_validationは挙動が分からなくなるので（コントローラで定義する方が今後の見通しがよくなる）、できれば使いたくないですが一旦OKです！

（そのまま使っていると分からなくなるので、before_validationについてご自身でも理解しておいてください。）

2024-01-27 10:47 UTC, yoshichiba commented on app/models/user.rb
> +    self.beebits_name = "@#{beebits_name}" unless beebits_name.blank? || beebits_name.match?(/\A@[^@]+\z/)
`self.beebits_name`のselfの部分、ご自身で調べていただけますと！
（説明していない箇所 & よく使われる記述なので）

2024-01-27 10:54 UTC, hiroaki514 commented on app/views/devise/registrations/new.html.erb
> +    <%= f.text_field :beebits_name, id: 'beebits_name_input', autocomplete: 'off' %>
削除しました！

2024-01-27 11:26 UTC, hiroaki514 commented on app/models/user.rb
> +  before_validation :prepend_at_to_beebits_name
コントローラーに移動させてみました。ただ、＠が自動で入っていない様子でバリデーションエラーとなってしまいます。

2024-01-27 11:31 UTC, hiroaki514 commented on app/models/user.rb
> +    self.beebits_name = "@#{beebits_name}" unless beebits_name.blank? || beebits_name.match?(/\A@[^@]+\z/)
user.rbの上部に記載されているUserクラス(今回の場合)のbeebits_nameというものをself.と付けることで指定している？という感じでしょうか。

2024-01-27 13:08 UTC, hiroaki514 commented
@yoshichiba 
こちらありがとうございます、修正しました！
ただ、＠の挿入がされるように記述を移したと思うのですが、上手く挙動しないようでbeebits_nameのフォームに「user」のように入力した際に、本来は自動で「@user」となってほしいところが「user」のままバリデーションエラーとなってしまいました。
記述的におかしい点などありますでしょうか？

2024-01-28 03:39 UTC, yoshichiba commented on app/models/user.rb
> +  before_validation :prepend_at_to_beebits_name
紛らわしい表現ですみません。
実装が進んだ段階でコントローラ側に移動させたいので今回はモデルに記述するで問題ないです。
（before_validationについて理解できればOKです）

2024-01-28 03:40 UTC, yoshichiba commented on app/models/user.rb
> +    self.beebits_name = "@#{beebits_name}" unless beebits_name.blank? || beebits_name.match?(/\A@[^@]+\z/)
そうですね。
省略も可能なのですが、明示的に書いた方が分かりやすいためselfは書く場合が多いです。

2024-01-29 14:42 UTC, hiroaki514 commented
@yoshichiba 
routes.rbにregistrations_controllerを利用するための記述が不足していたのが原因だったようです。
コントローラーへの記述移動で@が自動挿入されない問題は解決しました。

ただ別の問題が発生しています。
・入力が「USER」であれば「@USER」の形式で保存される
・「@user」「@USER」「@UsEr」「@useR」などは同一のものとして、重複してはいけない

上記で考えているのですが、入力がいずれの形式であっても保存される際に「@user」のように小文字に成形されてしまい、バリデーションを保ちつつ入力状態のまま保存する事が叶っていません。

2024-01-29 14:58 UTC, yoshichiba commented on app/models/user.rb
> +                       length: { maximum: 15 }
質問の意図を汲み取れているか微妙なのですが、大文字小文字の区別であれば、ここの`uniqueness: { case_sensitive: false, on: :create },`が何をしているか調べてみてください。

2024-02-01 11:42 UTC, yoshichiba approved these changes
LGTMです！

2024-02-01 11:42 UTC, merged