【feature】ログイン機能のテスト
hiroaki514/BeeBits pull request #64
Opened 2024-02-07 22:58 UTC by hiroaki514

## PRの目的
ログイン機能とユーザー登録機能のテストを新規追加します。

## 重点的に見て欲しいポイント

## 対象のissues

## 備考

2024-02-08 01:58 UTC, hiroaki514 commented
@yoshichiba 
こちらテストの実行を確認中なのですが、以下のルーティングに関するエラーが出てしまっています。
devise関連のルーティングが2つ読み込めていないようなのですが、contents_management_appと比べて特に違う記述なども無いようです、なにが原因となっているでしょうか？

```
$ docker compose run web bundle exec rspec
 Container beebits-db-1  Running
env: can't execute 'ruby.exe': No such file or directory
.*DEPRECATION WARNING: Setting action_dispatch.show_exceptions to false is deprecated. Set to :none instead. (called from block (3 levels) in <main> at /app/spec/requests/users_spec.rb:8)
DEPRECATION WARNING: Setting action_dispatch.show_exceptions to false is deprecated. Set to :none instead. (called from block (3 levels) in <main> at /app/spec/requests/users_spec.rb:8)
FDEPRECATION WARNING: Setting action_dispatch.show_exceptions to false is deprecated. Set to :none instead. (called from block (3 levels) in <main> at /app/spec/requests/users_spec.rb:15)
DEPRECATION WARNING: Setting action_dispatch.show_exceptions to false is deprecated. Set to :none instead. (called from block (3 levels) in <main> at /app/spec/requests/users_spec.rb:15)
F**

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Timelines GET /index add some examples (or delete) /app/spec/requests/timelines_spec.rb
     # Not yet implemented
     # ./spec/requests/timelines_spec.rb:5

  2) users/create.html.erb add some examples to (or delete) /app/spec/views/users/create.html.erb_spec.rb
     # Not yet implemented
     # ./spec/views/users/create.html.erb_spec.rb:6

  3) users/new.html.erb add some examples to (or delete) /app/spec/views/users/new.html.erb_spec.rb
     # Not yet implemented
     # ./spec/views/users/new.html.erb_spec.rb:6

Deprecation Warnings:

Rails 7.1 has deprecated the singular fixture_path in favour of an array.You should migrate to plural:


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

Failures:

  1) Users GET /new returns http success
     Failure/Error: get '/users/new'

     ActionController::RoutingError:
       No route matches [GET] "/users/new"
     # /usr/local/bundle/gems/railties-7.1.3/lib/rails/rack/logger.rb:37:in `call_app'
     # /usr/local/bundle/gems/railties-7.1.3/lib/rails/rack/logger.rb:24:in `block in call'
     # /usr/local/bundle/gems/railties-7.1.3/lib/rails/rack/logger.rb:24:in `call'
     # /usr/local/bundle/gems/rack-3.0.8/lib/rack/method_override.rb:28:in `call'
     # /usr/local/bundle/gems/rack-3.0.8/lib/rack/runtime.rb:24:in `call'
     # /usr/local/bundle/gems/rack-3.0.8/lib/rack/sendfile.rb:114:in `call'
     # /usr/local/bundle/gems/railties-7.1.3/lib/rails/engine.rb:536:in `call'
     # /usr/local/bundle/gems/rack-test-2.1.0/lib/rack/test.rb:360:in `process_request'
     # /usr/local/bundle/gems/rack-test-2.1.0/lib/rack/test.rb:153:in `request'
     # ./spec/requests/users_spec.rb:8:in `block (3 levels) in <main>'

  2) Users GET /create returns http success
     Failure/Error: get '/users/create'

     ActionController::RoutingError:
       No route matches [GET] "/users/create"
     # /usr/local/bundle/gems/railties-7.1.3/lib/rails/rack/logger.rb:37:in `call_app'
     # /usr/local/bundle/gems/railties-7.1.3/lib/rails/rack/logger.rb:24:in `block in call'
     # /usr/local/bundle/gems/railties-7.1.3/lib/rails/rack/logger.rb:24:in `call'
     # /usr/local/bundle/gems/rack-3.0.8/lib/rack/method_override.rb:28:in `call'
     # /usr/local/bundle/gems/rack-3.0.8/lib/rack/runtime.rb:24:in `call'
     # /usr/local/bundle/gems/rack-3.0.8/lib/rack/sendfile.rb:114:in `call'
     # /usr/local/bundle/gems/railties-7.1.3/lib/rails/engine.rb:536:in `call'
     # /usr/local/bundle/gems/rack-test-2.1.0/lib/rack/test.rb:360:in `process_request'
     # /usr/local/bundle/gems/rack-test-2.1.0/lib/rack/test.rb:153:in `request'
     # ./spec/requests/users_spec.rb:15:in `block (3 levels) in <main>'

1 deprecation warning total

Finished in 0.48938 seconds (files took 9.25 seconds to load)
6 examples, 2 failures, 3 pending

Failed examples:

rspec ./spec/requests/users_spec.rb:7 # Users GET /new returns http success
rspec ./spec/requests/users_spec.rb:14 # Users GET /create returns http success

```

2024-02-08 02:05 UTC, yoshichiba commented
rspec ./spec/requests/users_spec.rb:7 # Users GET /new returns http success
rspec ./spec/requests/users_spec.rb:14 # Users GET /create returns http success

こちらのスペックが失敗してるのですが、こちらは不必要ではないでしょうか？

（エラー文を最後まで見ていただけると、何が原因なのか大体わかるので今後は見てみましょう）

2024-02-10 11:06 UTC, hiroaki514 commented
@yoshichiba 
ユーザー登録についてのテスト追加が完了しました。
ご確認よろしくお願いします！

2024-02-11 09:58 UTC, yoshichiba requested changes
Gemなど不要な変更が入っているので、そちらは差分に含まれないようにしていただけると🙏

2024-02-12 02:26 UTC, hiroaki514 commented
@yoshichiba 
Rspec実行時のエラー表示解決で変更したGemfileは以下で変更するように修正しました！
https://github.com/hiroaki514/BeeBits/pull/95

2024-02-12 02:39 UTC, yoshichiba commented on spec/rails_helper.rb
> +  config.fixture_paths = "#{Rails.root}/spec/fixtures"
ここの変更は意図していますでしょうか？

2024-02-12 02:39 UTC, yoshichiba commented on spec/models/user_spec.rb
> +      end
ここは未記入ですが、追加は別PRということでしょうか？

2024-02-12 02:39 UTC, yoshichiba commented on Gemfile.lock
> +  pry-rails
Gemfile.lockが更新されていません。
bundle installも実行していたたげると！

2024-02-12 03:09 UTC, hiroaki514 commented on Gemfile.lock
> +  pry-rails
bundle installを実行し差分を解消しました！

2024-02-12 03:10 UTC, hiroaki514 commented on spec/models/user_spec.rb
> +      end
こちら追々にSMS認証などが試せる段階で必須に変更予定で、項目だけ忘れないように追加しています！

2024-02-12 03:11 UTC, hiroaki514 commented on spec/rails_helper.rb
> +  config.fixture_paths = "#{Rails.root}/spec/fixtures"
Railsのバージョンによりfixture_pathが非推奨になった様で、実行のたびにエラーが出ていたため最新の推奨であるfixture_pathsに修正しました！

2024-02-12 03:11 UTC, hiroaki514 commented
@yoshichiba 
よろしくお願いします！

2024-02-12 05:42 UTC, yoshichiba approved these changes
OKです！

2024-02-12 06:26 UTC, merged